FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
LABEL org.opencontainers.image.source="https://github.com/Dreamacro/clash"

RUN mkdir /etc/clash && \
    curl -L -o /etc/clash/Country.mmdb https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb && \
    chmod -R g+ws /etc/clash

COPY  bin/clash-linux-amd64 /usr/local/bin/clash
ENTRYPOINT ["/clash"]